### ISSUE TITLE
Error when downloading .mov

### ISSUE THREAD

**Issue by igor9silva** [graysky2/xscreensaver-aerial#1]
Hi,

I'm receiving this error:

```
curl: (23) Failed writing body (2560 != 2880)
==> ERROR: Failure while downloading b3-2.mov
    Aborting...
==> ERROR: Makepkg was unable to build xscreensaver-aerial.
```

When trying to install via yaourt (`yaourt -S xscreensaver-aerial`).

I've tried removing `b3-2.mov` from the PKGBUILD then the error occurs on `b3-3.mov` and so on.

If I manually curl the file I can download it normally, as well trough the browser.

As I know, this error occurs when a piped program closes the read stream before it has finished downloading `(e.g. curl "URL" -o "FILE" | grep "a", will fail when grep finds 'a')`.

Any idea?

**Comment by graysky2** [comment]
Does it work as expected if you build with `makepkg -s`

**Comment by igor9silva** [comment]
Yes, it does.

**Comment by graysky2** [comment]
OK... something jacked-up with your AUR helper.  They seem to be troublesome with more and more packages.  Anyway, glad you have it working.  Enjoy.
