### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by betab** [graysky2/xscreensaver-aerial#10]
Thank you for working on this. I am running Linux Mint 18.3 Cinnamon. I moved the .sh file to /usr/lib/xscreensaver/atv4, made it executable but could not find the line with programs: in the ~/.xscreensaver file. I added the line anyway but it still does not show up in xscreensaver. Any thoughts? Am I missing something?

Thanks!

**Comment by graysky2** [comment]
Perhaps mint uses another location.  You need to put that file in where ever the xscreensaver package puts the other ones.  On Arch, it's `/usr/lib/xscreensaver/` ... I am unfamiliar with the package manager you're using, but see if you can get it to list out all the files in the xscreensaver package.  Look for `sonar` which is an old one.

For ubuntu, it seems there are auxiliary packages that provide the individual screensavers:
https://packages.ubuntu.com/bionic/amd64/xscreensaver-gl/filelist
https://packages.ubuntu.com/bionic/amd64/xscreensaver-gl-extra/filelist
https://packages.ubuntu.com/bionic/amd64/xscreensaver-data/filelist

Perhaps you are lacking these or mint does something similar?

**Comment by betab** [comment]
Thank you for the response. All the xscreensaver packages are in `/usr/lib/xscreensaver/`. I see sonar in there along with all the other screensaver files. Here is what I see when I do: ` sudo nano ~/.xscreensaver`
![untitled](https://user-images.githubusercontent.com/6155149/43666478-e0d45366-9728-11e8-868c-eb6973d8254a.png)

I am a novice so sorry if I am missing something here that is a simple mistake . .

**Comment by graysky2** [comment]
Sorry, this fell off my radar.... post the entire `~/.xscreensaver`

**Comment by betab** [comment]
No worries. That was the entire `~/.xscreensaver` when I entered `sudo nano ~/.xscreensaver`. There was nothing more there...

**Comment by graysky2** [comment]
Did you follow the readme?
> 2. Edit ~/.xscreensaver to add support for it to see this script. Look for the line that beings with "programs:" and simply add the following to the file: "ATV4" atv4 \n\

**Comment by betab** [comment]
Yes, but there was no linie that began with "programs:" to add "ATV4" atv4 \n\. I tried adding the line in there but it didn't do anything

**Comment by graysky2** [comment]
@betab - Are you still facing this?

**Comment by betab** [comment]
@graysky2 Yes, I gave up. Mint appears to run xscreensaver differently. I don't know this well enough to figure it out. Thanks for trying to help. I really wanted it to work.

**Comment by graysky2** [comment]
I don't see how it's different since xscreensaver is xscreensaver.... Post your entire `~/.xscreensaver` but no need to invoke with sudo.  You might have jacked up your permissions to that file.  Recommend that you restore your user's permissions on your homedir or at the very least that particular file...

Find out your username and primary group example from my system:
```% id
uid=1020(gsky) gid=985(users) groups=985(users
```

So for me I would issue:
```
sudo chown -R gsky:users /home/gsky
```

Try that then delete or move your xscreensaver pref file so it is recreated:
```
mv ~/.xscreensaver ~/x-backup
```

Now close and reload xscreensaver and let it re-write your preferences file.  Then edit WITHOUT sudo as I describe.

**Comment by graysky2** [comment]
@betab - Ping?

**Comment by betab** [comment]
Sorry, I've been busy. I will go back and try to fix the file. Thanks for following up!

**Comment by betab** [comment]
Recreated. Still no line that says programs:

`
# XScreenSaver Preferences File
# Generated: 2018-10-26 15:45:07.749263
# by the xscreensaver plugin for cinnamon-screensaver
# Use xscreensaver-demo to customize

visualID:   default
installColormap:    True
font:       *-medium-r-*-140-*-m-*

grabDesktopImages:  False
grabVideoFrames:    False
chooseRandomImages: True
imageDirectory: /home/brandon/Pictures

mode:       random
selected:   -1

textMode:   literal
textLiteral:    Cinnamon
textFile:
textProgram:    fortune

pointerPollTime:    0:00:05
pointerHysteresis:  10
GetViewPortIsFullOfLies:False
procInterrupts: True
`

**Comment by graysky2** [comment]
That is crazy..  please try this:

```
killall xscreensaver
mv ~/.xscreensaver ~/xs-backup
xscreensaver-demo
```

For me just now:
```
# XScreenSaver Preferences File
# Written by xscreensaver-demo 5.40 for gsky on Fri Oct 26 19:00:38 2018.
# https://www.jwz.org/xscreensaver/

timeout:	0:10:00
cycle:		0:10:00
lock:		False
lockTimeout:	0:00:00
passwdTimeout:	0:00:30
visualID:	default
installColormap:    True
verbose:	False
timestamp:	True
splash:		True
splashDuration:	0:00:05
demoCommand:	xscreensaver-demo
prefsCommand:	xscreensaver-demo -prefs
nice:		10
memoryLimit:	0
fade:		True
unfade:		False
fadeSeconds:	0:00:03
fadeTicks:	20
captureStderr:	True
ignoreUninstalledPrograms:False
font:		*-medium-r-*-140-*-m-*
dpmsEnabled:	False
dpmsQuickOff:	False
dpmsStandby:	2:00:00
dpmsSuspend:	2:00:00
dpmsOff:	4:00:00
grabDesktopImages:  True
grabVideoFrames:    False
chooseRandomImages: False
imageDirectory:	

mode:		random
selected:	-1

textMode:	file
textLiteral:	XScreenSaver
textFile:	
textProgram:	fortune
textURL:	https://en.wikipedia.org/w/index.php?title=Special:NewPages&feed=rss

programs:								      \
				maze -root				    \n\
  GL: 				superquadrics -root			    \n\
				attraction -root			    \n\
...
```

**Comment by betab** [comment]
Just did but this is what I got:

`$ killall xscreensaver
xscreensaver: no process found`

**Comment by graysky2** [comment]
That's fine... just means it's not running (probably that step isn't required).  Key is to remove that file and recreate it with `xscreensaver-demo`

**Comment by betab** [comment]
Looks like it's removed. Log out?

**Comment by betab** [comment]
I restarted and it recreated it:

# XScreenSaver Preferences File
# Generated: 2018-10-26 16:30:06.756260
# by the xscreensaver plugin for cinnamon-screensaver
# Use xscreensaver-demo to customize

visualID:   default
installColormap:    True
font:       *-medium-r-*-140-*-m-*

grabDesktopImages:  False
grabVideoFrames:    False
chooseRandomImages: True
imageDirectory: /home/brandon/Pictures

mode:       random
selected:   -1

textMode:   literal
textLiteral:    Cinnamon
textFile:
textProgram:    fortune

pointerPollTime:    0:00:05
pointerHysteresis:  10
GetViewPortIsFullOfLies:False
procInterrupts: True

**Comment by betab** [comment]
should I be doing something with xscreensaver-demo since it says to use xscreensaver-demo to customize?

**Comment by graysky2** [comment]
You run `xscreensaver-demo` to setup your preferences.  What happens when you run it, and select any screensaver from the menu (i.e. to change the options)?

**Comment by betab** [comment]
It does not seem to have it. I installed it from apt (now I have 2 versions) and this is what I got:

$ xscreensaver-demo

(xscreensaver-demo:11139): libglade-WARNING **: Could not load support for `gnome': libgnome.so: cannot open shared object file: No such file or directory

It did open up the gui to customize but not sure what to do since I already have the system version. It seems the system version is configured differently...

**Comment by betab** [comment]
Sorry, that may be confusing. I installed xscreensaver again, so now I have 2 versions

**Comment by graysky2** [comment]
Are you still facing this issue... I'm not sure how to help?

**Comment by betab** [comment]
Yes. I gave up. Have you had anyone else on Mint able to install it?
