### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Brendan92** [graysky2/xscreensaver-aerial#11]
I'm getting this error:

xscreensaver could not execute "atv4": Permission Denied
exited abnormally(code 1)

Am I being a noob or how could I fix this?

**Comment by graysky2** [comment]
What is the output of `stat /usr/lib/xscreensaver/atv4`

**Comment by BrendanThysse** [comment]
File: /usr/lib/xscreensaver/atv4
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: b302h/45826d	Inode: 396508      Links: 2
Access: (0777/drwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-08-20 17:05:12.817868564 +0200
Modify: 2018-08-20 17:10:26.619840492 +0200
Change: 2018-08-20 18:10:03.200600764 +0200
 Birth: -

**Comment by graysky2** [comment]
Hmmm... 777 is a bit overkill, 755 should be fine, but I was thinking it wasn't +x but it is... not sure why you're getting that.

**Comment by graysky2** [comment]
@BrendanThysse - Ping?

**Comment by Brendan92** [comment]
@graysky2 Could not figure this out, think it could be something with the OS, running RASPBIAN.

**Comment by graysky2** [comment]
Doubt it's with the OS... xscreensaver is xscreensaver

**Comment by yizhilee** [comment]
I got this too:  
xscreensaver could not execute "atv4-1080": Permission Denied
exited abnormally(code 1)

**Comment by yizhilee** [comment]
@graysky2 @Brendan92 "atv4" should be a file, not a directory.
