### ISSUE TITLE
Not working on Lock Screen

### ISSUE THREAD

**Issue by parkour86** [graysky2/xscreensaver-aerial#13]
xscreensaver-aerial works fine when logged into my laptop but when I lock my screen the screensaver doesn't run. Is there a workaround to get it to run while the computer is locked?

**Comment by graysky2** [comment]
...do any screensavers work when locked?

**Comment by parkour86** [comment]
Not that I know of. This is the first time I enabled a screensaver in Ubuntu.

**Comment by graysky2** [comment]
If none of the others work, there is something wrong with your setup.

**Comment by parkour86** [comment]
I'm unable to find any screensaver that works with the lock screen. I'll go ahead and close this.
