### ISSUE TITLE
xscreensaver-aerial-videos is gone in aur

### ISSUE THREAD

**Issue by shokinn** [graysky2/xscreensaver-aerial#14]
Hi,
the xscreensaver-aerial-videos package is not in the aur anymore.

Will it be back in some time?

**Comment by shokinn** [comment]
Ok, missed it.
It's there "xscreensaver-aerial-videos-1080, xscreensaver-aerial-videos-4k".
Than the optional dependency in the xscreensaver-aerial package is wrog. it points still to "xscreensaver-aerial-videos".

**Comment by graysky2** [comment]
You're right.  Thanks, fixed.
