### ISSUE TITLE
Add downloader script

### ISSUE THREAD

**Issue by vadbars** [graysky2/xscreensaver-aerial#16]
Do we need a script to add new video files? Apple will add a new videos.
We can use the downloader script like this one:
https://gist.github.com/xd1936/ab0936e04de87c2cdcf5

It uses aria2c instead of wget. Perhaps it is more convenient and can also be used.

Thanks for the great job!

**Comment by graysky2** [comment]
Since I provide a PKGBUILD for Arch Linux, I just mirrored those files with wget.  An aria2c solution works too.
