### ISSUE TITLE
Screensaver does not show up in the xscreensaver-demo list after installation

### ISSUE THREAD

**Issue by curusarn** [graysky2/xscreensaver-aerial#18]
I installed `xscreensaver-aerial` using `yaourt -S xscreensaver-aerial` and when I launched `xscreensaver-demo` I didn't see the screensaver in the list.

I only saw it in the list when I added `programs: atv4-1080` to `~/.xscreensaver` and copied `atv4-1080` to a directory that is in my `PATH`.

I expected to see the screensaver after installation.

Cheers.

**Comment by graysky2** [comment]
Dunno how yaourt does it but if you used makepkg and pacman, you would have seen the instructions needed to get it to work:
```
post_install() {
  echo '------------------------------------------------------------------------------------'
  echo ' You must edit ~/.xscreensaver to add support for this screensaver'
  echo ' Find the line "programs:" and simply add the following below it:'
  echo ' "ATV4-1080" atv4-1080 \n\'
  echo ' "ATV4-4k" atv4-4k \n\'
  echo '------------------------------------------------------------------------------------'
}
```

EDIT: AUR helpers are seldom helpful ;p
