### ISSUE TITLE
Real fullscreen

### ISSUE THREAD

**Issue by bobchao** [graysky2/xscreensaver-aerial#2]
Idea: Since this is a screensaver, it should displayed in full-screen without blackbars on top and bottom, in any screen aspect ratio.

I'm lacking of the knowledge on getting user's screen aspect ratio via shell script, but anyway I added --video-zoom=0.1 on my laptop. Maybe someone can do it with a better method.

**Comment by graysky2** [comment]
On my machine, the code as written doesn't display any backbars.  As a test, can you manually try the following and verify that you get blackbars:
 mpv --really-quiet --no-audio --fs --no-stop-screensaver foo.mov

**Comment by graysky2** [comment]
Any update from your end?
