### ISSUE TITLE
Possibility of Creating Custom Config Directory

### ISSUE THREAD

**Issue by ZLima12** [graysky2/xscreensaver-aerial#20]
I was simply going to patch the script to do this, but would it be of interest to use `~/.config/xscreensaver-aerial/` as the config directory instead of just `~/.config`? I think that this would help keep things organized. If you'd rather keep it as-is, I understand, but I thought I should ask.

**Comment by graysky2** [comment]
I could but I'm not too concerned over writing out to just `$XDG_CONFIG_HOME`
