### ISSUE TITLE
New underwater (and other) videos

### ISSUE THREAD

**Issue by schneefisch** [graysky2/xscreensaver-aerial#25]
Hi, 
there are new videos,
sadly I did not discover the 4K resources.

`
_url4="https://sylvan.apple.com/Videos"

for i in BO_A018_C029_SDR_20190812_SDR_2K_AVC.mov \
    BO_A014_C008_SDR_20190719_SDR_2K_AVC.mov \
    BO_A014_C023_SDR_20190717_F240F3709_SDR_2K_AVC.mov \
    BO_A012_C031_SDR_20190726_SDR_2K_AVC.mov \
    comp_A050_C004_1027V8_v16_SDR_FINAL_20180706_SDR_2K_AVC.mov \
    comp_A105_C002_v06_SDR_FINAL_25062018_SDR_2K_AVC \
    comp_GMT060_117NC_363D_1034_AUSTRALIA_v35_SDR_PS_FINAL_20180731_SDR_2K_AVC \
    comp_A351_C001_v06_SDR_PS_20180725_SDR_2K_AVC.mov \
    comp_DB_D011_C010_PSNK_DENOISE_v19_SDR_PS_20180914_SDR_2K_AVC.mov \
    comp_DB_D002_C003_PSNK_v04_SDR_PS_20180914_SDR_2K_AVC.mov \
    comp_GL_G010_C006_PSNK_NOSUN_v12_SDR_PS_FINAL_20180709_SDR_2K_AVC.mov \
    comp_H012_C009_PS_v01_SDR_PS_20180925_SDR_2K_AVC.mov \
    AK_A004_C012_SDR_20191217_SDR_2K_AVC.mov \
    CR_A009_C007_SDR_20191113_SDR_2K_AVC.mov \
    DL_B002_C011_SDR_20191122_SDR_2K_AVC.mov \
    MEX_A006_C008_SDR_20190923_SDR_2K_AVC.mov \
    FK_U009_C004_SDR_20191220_SDR_2K_AVC.mov \
    KP_A010_C002_SDR_20190717_SDR_2K_AVC.mov \
    PA_A004_C003_SDR_20190719_SDR_2K_AVC.mov \
    PA_A002_C009_SDR_20190730_ALT01_SDR_2K_AVC.mov \
    PA_A010_C007_SDR_20190717_SDR_2K_AVC.mov \
    RS_A008_C010_SDR_20191218_SDR_2K_AVC.mov \
    SE_A016_C009_SDR_20190717_3m30s_SDR_2K_AVC.mov \
    g201_AK_A003_C014_SDR_20191113_SDR_2K_AVC.mov \
    g201_WH_D004_L014_SDR_20191031_SDR_2K_AVC.mov \
    g201_TH_803_A001_8_SDR_20191031_SDR_2K_AVC.mov \
    g201_TH_804_A001_8_SDR_20191031_SDR_2K_AVC.mov \
    g201_CA_A016_C002_SDR_20191114_SDR_2K_AVC.mov; do
    wget --no-check-certificate "$_url4/$i"
    chmod 644 $(pwd)/$i
done
`

**Comment by graysky2** [comment]
@schneefisch - Took me a while but pinging to see if you found a 4k link?

**Comment by graysky2** [comment]
https://github.com/graysky2/xscreensaver-aerial/commit/c688a5ece6ed643eb5db721398cdda143d4025ea
