### ISSUE TITLE
Script doesn't kill mpv instances

### ISSUE THREAD

**Issue by Aditeya** [graysky2/xscreensaver-aerial#28]
I keep finding my ram usage increases and cause seems to mpv. The script doesn't kill the mpv instance so more mpv instances are spawned which take a huge chunk of memory.

```
[aditeya@nemo ~]$ ps aux | grep mpv
aditeya    17388  0.3  3.8 3858336 316068 ?      SNl  12:47   1:55 mpv --really-quiet --no-audio --fs --no-stop-screensaver --wid=0x1000006 --panscan=1.0 https://sylvan.apple.com/Aerials/2x/Videos/FK_U009_C004_SDR_20191220_SDR_2K_HEVC.mov
aditeya    21270  0.2  1.3 3518788 112560 ?      SNl  14:22   1:03 mpv --really-quiet --no-audio --fs --no-stop-screensaver --wid=0x100008C --panscan=1.0 /mnt/harddisk/programs/ATV4/DB_D011_C009_2K_SDR_HEVC.mov
aditeya    26173  0.3  0.3 3519668 24632 ?       SNl  16:37   1:16 mpv --really-quiet --no-audio --fs --no-stop-screensaver --wid=0x10002EF --panscan=1.0 https://sylvan.apple.com/Aerials/2x/Videos/PA_A010_C007_SDR_20190717_SDR_2K_HEVC.mov
aditeya    26271  1.4  0.8 3651760 72176 ?       SNl  16:40   5:11 mpv --really-quiet --no-audio --fs --no-stop-screensaver --wid=0x10002F2 --panscan=1.0 https://sylvan.apple.com/Aerials/2x/Videos/comp_LA_A008_C004_ALTB_ED_FROM_FLAME_RETIME_v46_SDR_PS_20180917_SDR_2K_HEVC.mov
aditeya    26644  0.5  0.4 3519672 33956 ?       SNl  16:57   1:42 mpv --really-quiet --no-audio --fs --no-stop-screensaver --wid=0x10002F5 --panscan=1.0 https://sylvan.apple.com/Aerials/2x/Videos/comp_LA_A005_C009_PSNK_ALT_v09_SDR_PS_201809134_SDR_2K_HEVC.mov
aditeya    26871  0.7  0.3 3518788 29328 ?       SNl  17:05   2:22 mpv --really-quiet --no-audio --fs --no-stop-screensaver --wid=0x10002F8 --panscan=1.0 /mnt/harddisk/programs/ATV4/comp_CH_C007_C011_PSNK_v02_SDR_PS_FINAL_20180709_SDR_2K_HEVC.mov
aditeya    27166  0.2  0.3 3519668 29824 ?       SNl  17:18   0:53 mpv --really-quiet --no-audio --fs --no-stop-screensaver --wid=0x10002FB --panscan=1.0 https://sylvan.apple.com/Aerials/2x/Videos/comp_HK_H004_C001_PSNK_DENOISE_v14_SDR_PS_FINAL_20180731_SDR_2K_HEVC.mov
aditeya    27531  0.0  0.4 3519668 35280 ?       SNl  17:29   0:17 mpv --really-quiet --no-audio --fs --no-stop-screensaver --wid=0x10002FE --panscan=1.0 https://sylvan.apple.com/Aerials/2x/Videos/comp_H007_C003_PS_v01_SDR_PS_20180925_SDR_2K_HEVC.mov
aditeya    27821  0.1  0.3 3519664 31732 ?       SNl  17:39   0:25 mpv --really-quiet --no-audio --fs --no-stop-screensaver --wid=0x1000301 --panscan=1.0 https://sylvan.apple.com/Aerials/2x/Videos/comp_LW_L001_C003__PSNK_DENOISE_v04_SDR_PS_FINAL_20180803_SDR_2K_HEVC.mov
aditeya    28024  0.6  1.1 3518792 90944 ?       SNl  17:46   1:56 mpv --really-quiet --no-audio --fs --no-stop-screensaver --wid=0x1000304 --panscan=1.0 /mnt/harddisk/programs/ATV4/DB_D001_C001_2K_SDR_HEVC.mov
aditeya    28322  0.4  1.5 3519664 124304 ?      SNl  17:58   1:05 mpv --really-quiet --no-audio --fs --no-stop-screensaver --wid=0x1000307 --panscan=1.0 https://sylvan.apple.com/Aerials/2x/Videos/g201_AK_A003_C014_SDR_20191113_SDR_2K_HEVC.mov
aditeya    28562  0.4  1.8 3519668 147796 ?      SNl  18:08   1:05 mpv --really-quiet --no-audio --fs --no-stop-screensaver --wid=0x100030A --panscan=1.0 https://sylvan.apple.com/Aerials/2x/Videos/comp_GL_G002_C002_PSNK_v03_SDR_PS_20180925_SDR_2K_HEVC.mov
aditeya    29169  1.2  1.7 3519668 140372 ?      SNl  18:24   3:07 mpv --really-quiet --no-audio --fs --no-stop-screensaver --wid=0x1000310 --panscan=1.0 https://sylvan.apple.com/Aerials/2x/Videos/comp_HK_H004_C010_PSNK_v08_SDR_PS_20181009_SDR_2K_HEVC.mov
aditeya    31042  0.1  1.5 3519664 123972 ?      SNl  19:27   0:14 mpv --really-quiet --no-audio --fs --no-stop-screensaver --wid=0x100041F --panscan=1.0 https://sylvan.apple.com/Aerials/2x/Videos/PA_A002_C009_SDR_20190730_ALT01_SDR_2K_HEVC.mov
aditeya    31100  2.4  1.5 3519808 125796 ?      SNl  19:27   4:29 mpv --really-quiet --no-audio --fs --no-stop-screensaver --wid=0x1000422 --panscan=1.0 /mnt/harddisk/programs/ATV4/HK_H004_C008_2K_SDR_HEVC.mov
aditeya    31595  0.6  4.0 3858336 333760 ?      SNl  19:47   1:02 mpv --really-quiet --no-audio --fs --no-stop-screensaver --wid=0x10005FC --panscan=1.0 https://sylvan.apple.com/Aerials/2x/Videos/comp_N008_C009_PS_v01_SDR_PS_20180925_SDR_2K_HEVC.mov
aditeya    32409  0.0  1.4 3518788 118616 ?      SNl  20:18   0:07 mpv --really-quiet --no-audio --fs --no-stop-screensaver --wid=0x10007B3 --panscan=1.0 /mnt/harddisk/programs/ATV4/HK_B005_C011_2K_SDR_HEVC.mov
aditeya    32687  0.4  1.5 3519668 125008 ?      SNl  20:28   0:34 mpv --really-quiet --no-audio --fs --no-stop-screensaver --wid=0x10007B6 --panscan=1.0 https://sylvan.apple.com/Aerials/2x/Videos/comp_H012_C009_PS_v01_SDR_PS_20180925_SDR_2K_HEVC.mov
aditeya    38592  0.0  0.0   6304  2116 pts/0    S+   22:30   0:00 grep --colour=auto mpv

```

I find this only happens when I leave the computer to run for a while so a lot of videos play. However, if one video plays, the mpv instance is killed. I usually just use `killall mpv` but its getting annoying to deal with.

**Comment by graysky2** [comment]
@kevincox - Do you have any insights?  The code to which @Aditeya refers I borrowed from your https://github.com/kevincox/xscreensaver-videos

https://github.com/graysky2/xscreensaver-aerial/blob/master/atv4-4k.sh#L159-L178

**Comment by kevincox** [comment]
I would check if mpv does some funny forking. I would try `pstree` to see if it is actually inside the session.

**Comment by graysky2** [comment]
@kevincox - I am pretty unfamiliar with `pstree` but here is the output on my user when I too can see this bug.

1) Run  `xscreensaver-demo` and select ATV4 (allow the preview to play for a few sec)
2) Close `xscreensaver-demo` and see that mpv is still running.
3) Run  `pstree youruser`

Any thoughts?

```
% pstree
systemd─┬─crond───8*[crond───sh───backdrop-random───xfdesktop───{xfdesktop}]
        ├─dbus-daemon
        ├─dnsmasq
        ├─gnome-keyring-d─┬─ssh-agent
        │                 └─3*[{gnome-keyring-d}]
        ├─mpv───7*[{mpv}]
        ├─polkitd───11*[{polkitd}]
        ├─python
...
```

Interestingly, if I trigger `xscreensaver-command -activate` the script works as expected and `mpv` is killed as I expect (it does not remain per `ps sux | grep mpv`).

**Comment by kevincox** [comment]
Looks like mpv isn't a child of the screensaver process which probably breaks the killing. I would check if it has a `--foreground` flag or something to avoid that.

**Comment by graysky2** [comment]
@kevincox - Thanks for consulting on this.  I do not see anything obvious like that when I run `mpv --list-options`

**Comment by cryptoquick** [comment]
I just ran into this problem, it was taking up 40GB of RAM on my machine. Poof, 40GB free after `kilall mpv`. So, that's gonna be a bit inconvenient...

**Comment by graysky2** [comment]
@cryptoquick - We need to implement @kevincox suggestion with mpv.

**Comment by dchou-zxy** [comment]
Is there a fix for this?

**Comment by Aditeya** [comment]
So I saw this video by distrotube where he made a script for playing ambient sounds and i decided to check his script. I found he uses ffplay a utility from ffmpeg. Would it be better to switch to ffplay, from mpv, and see if this issue is present there?

[the script DT made](https://gitlab.com/dwt1/dmscripts/-/blob/master/scripts/dmsounds)

**Comment by graysky2** [comment]
Possibly.  It depends on how `ffplay` responds to the kill signal and if it can be a surrogate for `mpv` in this context.

EDIT: I don't think `ffplay` is screensaver aware, so triggering it via this script will run out of control.

You can try it.  I tested it replacing [line 173](https://github.com/graysky2/xscreensaver-aerial/blob/master/atv4-2k.sh#L173) with the following:

```
ffplay -fs -loglevel quiet -hide_banner -an -noborder -exitonkeydown -exitonmousedown "$APPLEURL/$useit" &
```

1) Previewing the hack in `xscreensaver-demo` results in it running in a loop.
2) There is no way to end the loop it seems when it is triggered by `xscreensaver`.

Maybe the cli switches can be adjusted to give the desired effect.

@Aditeya - Can you play with it and report back?

**Comment by Aditeya** [comment]
Alright got it, also could you elaborate on what cli switches mean?, I'm quite new to shell scripting.

**Comment by graysky2** [comment]
I just read through the man page for ffplay and selected what I thought were appropriate.

**Comment by Aditeya** [comment]
Alright so I checked `ffplay` flags and tried a few things but nothing worked. I then checked kevincox's script and found it uses `mplayer`. I then found a command on this [ubuntu form](https://ubuntuforums.org/showthread.php?t=2043619) for `mplayer` and modified it: 

```
mplayer -nosound -really-quiet -nolirc -nostop-xscreensaver -wid $XSCREENSAVER_WINDOW -fs "$movies/$useit" &
```

I tested it on my local video files and it works well and the problem is solved!. I haven't tested the links, however, playing the url from the terminal seems to work.

**Comment by graysky2** [comment]
@Aditeya - Thanks for sharing.  Can you please try the latest git and report back?  Worked for me in 5 min of testing.

**Comment by Aditeya** [comment]
It WORKS!!!

however you made a mistake on [line 169](https://github.com/graysky2/xscreensaver-aerial/blob/a531c1c19ed6ed9bc90e91fe3848df0191b9dbfc/atv4-4k.sh#L169)

it should be `"$movies/$useit"`

**Comment by graysky2** [comment]
Corrected, thanks.
