### ISSUE TITLE
Online mode

### ISSUE THREAD

**Issue by utack** [graysky2/xscreensaver-aerial#3]
Hi,

thanks for making this screensaver.
Have you considered adding an online mode?

Jakob

**Comment by graysky2** [comment]
No, don't know much about streaming with mpv nor did I think users would want to repeatedly download the same files.  Is this something you would do?

**Comment by utack** [comment]
It is a bit mean for the servers, but with a 128GB SSD in my Notebook and unlimited Internet traffic I'd consider it  
I will just reduce the amount of downloaded videos for now, that works too

**Comment by graysky2** [comment]
It's a good request.  I will implement.  Stay tuned.

**Comment by utack** [comment]
Thanks.

**Comment by graysky2** [comment]
Just need to adjust the PKGBUILD to a split one.  Will push the commit after breakfast.

**Comment by graysky2** [comment]
@utack - Please try v1.03 and let me know how it works for you.  Works for me.

**Comment by utack** [comment]
Yep works here too  
Thanks for adding it so quickly!

**Comment by graysky2** [comment]
YW. Enjoy!
