### ISSUE TITLE
Use VLC

### ISSUE THREAD

**Issue by Firesphere** [graysky2/xscreensaver-aerial#30]
Is it possible to use VLC instead of mplayer or mpv?

**Comment by graysky2** [comment]
Not sure ...why?  So many deps.

**Comment by Firesphere** [comment]
Playback on a Raspberry Pi 2 (yes, I know), seems smoother in VLC than MPlayer, so I figured, why not.

I only tried this from the GUI, not from terminal, though.

**Comment by graysky2** [comment]
You'd have to figure out if vlc is screensaver aware like mplayer is then figure out a set of cli switches for it.

**Comment by Firesphere** [comment]
The first part, it is. The last part of the CLI switches, I'll need to work out.

Cheers, I might give a PR at some stage, to easily switch between players, if people wish to do so, or something.
