### ISSUE TITLE
Screensaver doesn't appear in xscreensaver in Fedora 34, Gnome 40.4

### ISSUE THREAD

**Issue by vplagov** [graysky2/xscreensaver-aerial#32]
I made everything according to instructions.

The script is in place:

```
bash-5.1# ls -al /usr/lib/xscreensaver/
-rwxr-xr-x   1 root root  7832 Oct 14 01:11 atv4-2k
```

The correct entry is added to the `~/.xscreensaver` file:

```
bash-5.1# grep -A 1 -B 1 "ATV" .xscreensaver
programs:								      \
		     "ATV4-2k" 	atv4-2k					    \n\
				maze -root				    \n\

```

When I launch the `xscreensaver` application, I don't see the ATV screensaver:
![image](https://user-images.githubusercontent.com/16601852/137221917-b4abdc63-d25d-453b-9d14-853d88186b05.png)

**Comment by graysky2** [comment]
Not sure why it's not showing up.  As a test, make sure no instances of xscreensaver are running:
```
killall xscreensaver
killall xscreensaver-demo
```
 Restart it and check again.  If that doesn't work try deleting the config and re-creating it.

**Comment by vplagov** [comment]
@graysky2 I was restarting the computer several times. Killed all `xscreensaver` processes. No luck.

Does it matter who is the owner of the `/usr/lib/xscreensaver/atv4-2k`? Should it be root?
Also, might it be that on Fedora the location of the script should be different? I was tried to find the location the xscreensaver is using on Fedora, but didn't find anything specific.

**Comment by graysky2** [comment]
It should still appear in the list.

**Comment by cptn-cosmo** [comment]
I have the same problem with a fresh installation on Archlinux

**Comment by graysky2** [comment]
I do not know what to tell you guys... I just did a fresh install and it worked per the instruction.
```
You must edit ~/.xscreensaver to add support for this screensaver
    Find the line "programs:" and simply add the following below it:
    "ATV4-2k" atv4-2k \n\
    "ATV4-4k" atv4-4k \n\
```

My `~/.xscreensaver` looks like this:
```
...
textProgram:    fortune
textURL:        https://en.wikipedia.org/w/index.php?title=Special:NewPages&feed=rss
dialogTheme:    default

programs:                                                                     \
                     "ATV4-4k"  atv4-4k                                     \n\
-                               maze -root                                  \n\
...

**Comment by graysky2** [comment]
@plagov - if you are still wanting to try on Fedora, can you check where that distro installs the actual screensavers?  See: https://github.com/graysky2/xscreensaver-aerial/issues/34#issuecomment-1211446130

Feel free to re-open if that did not fix your issue.
