### ISSUE TITLE
Installation instruction for non-Arch has a two typo

### ISSUE THREAD

**Issue by daehenoc** [graysky2/xscreensaver-aerial#35]
Hi, the updated instructions for installing xscreensaver-aerial on Ubuntu contains two typo for step 1:

1. This text appears twice: "Copy atv4-2k.sh from this repo to $XSCREEN/atv4-2k and make it executable by running the following as the root user."
2. The 'cp/chmod' command is currently:
`cp atv4-2k.sh $XSCREEN/atv4-2k && chmod +x XSCREEN/xscreensaver/atv4-2k`
And it should be:
`cp atv4-2k.sh $XSCREEN/atv4-2k && chmod +x $XSCREEN/atv4-2k`

**Comment by graysky2** [comment]
Thanks
