### ISSUE TITLE
Fedora 25

### ISSUE THREAD

**Issue by metabsd** [graysky2/xscreensaver-aerial#4]
HI, I try to use it in Fedora 25 but I don't see it in xscreensaver-demo. I follow the step for other distro and make sure all thing is ok.

**Comment by graysky2** [comment]
Post the output of
`grep ATV ~/.xscreensaver`

**Comment by metabsd** [comment]
grep ATV ~/.xscreensaver
			"ATV4" 	atv4					    \n\

**Comment by graysky2** [comment]
Not sure why you do not see it... for me, it is the first entry under `programs`:
```
# XScreenSaver Preferences File
# Written by xscreensaver-demo 5.36 for facade on Mon Jan 30 15:46:56 2017.
# https://www.jwz.org/xscreensaver/
...
programs:                     \
      "ATV4"  atv4              \n\
-       maze -root            \n\
...
```

**Comment by kirasglimmer** [comment]
For me, it wasn't immediately obvious that I needed to copy the atv4.sh script from this repo.  I spent some time spinning my wheels on how the download script was to be used as the screen saver script.  Then I figured it out, and following the directions, I was able to get it working on Linux Mint 18.1.

**Comment by graysky2** [comment]
I'll try to make the readme more clear

**Comment by Daniel-Wang** [comment]
I have the same issue on Fedora 25.

grep ATV ~/.xscreensaver 
			"ATV4" 	atv4					    \n\

This is my .xscreensaver file:
 XScreenSaver Preferences File
 Written by xscreensaver-demo 5.36 for dwang on Wed Apr  5 17:26:10 2017.
 https://www.jwz.org/xscreensaver/

timeout:	0:10:00
cycle:		0:10:00
lock:		True
lockTimeout:	0:00:00
passwdTimeout:	0:00:15
visualID:	default
installColormap:    True
verbose:	False
timestamp:	True
splash:		False
splashDuration:	0:00:05
demoCommand:	xscreensaver-demo
prefsCommand:	xscreensaver-demo -prefs
nice:		10
memoryLimit:	0
fade:		True
unfade:		False
fadeSeconds:	0:00:03
fadeTicks:	20
captureStderr:	False
ignoreUninstalledPrograms:True
font:		*-medium-r-*-140-*-m-*
dpmsEnabled:	False
dpmsQuickOff:	False
dpmsStandby:	2:00:00
dpmsSuspend:	2:00:00
dpmsOff:	4:00:00
grabDesktopImages:  False
grabVideoFrames:    False
chooseRandomImages: True
imageDirectory:	/usr/share/backgrounds/images

mode:		one
selected:	129

textMode:	file
textLiteral:	XScreenSaver
textFile:	/etc/fedora-release
textProgram:	fortune -s
textURL:	http://planet.fedoraproject.org/rss20.xml

programs:								      \
			"ATV4" 	atv4					    \n\
				maze -root				    \n\
  GL: 				superquadrics -root			    \n\
				attraction -root			    \n\
				blitspin -root				    \n\
				
. . .

pointerPollTime:    0:00:05
pointerHysteresis:  10
windowCreationTimeout:0:00:30
initialDelay:	0:00:00
GetViewPortIsFullOfLies:False
procInterrupts:	True
xinputExtensionDev: False
overlayStderr:	True
authWarningSlack:   20

I changed my %PATH to add usr/li/xscreensaver/atv4, then it showed up, but it using it outputs a black screen.
screensaver:   signal: 0: child pid 32108 (atv4) exited abnormally (code 1).

**Comment by dmnrmr** [comment]
@Daniel-Wang in my case I needed to install mpv. `dnf install mpv`.
